### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kingofkillers91** [bilabon/chatgpt_telegram_bot#3]
First of all congrats.
How do i run the bot? shall i type "python main.py"?
plus, i'm not sure whether i have to create a second config.py in the folder settings and  set BOT_TOKEN, AI_TOKEN, ADMIN_USERNAME in that second file? Or should i just replace those value in the config.py you created.
I got confused because in the file you wrote " # You need to create config.py and set all these variables there", then on your github main page you don't mention to create a second config.py.
Can you explain?
Thanks

**Comment by bilabon** [comment]
python main.py - yes it's enough, but you need to use python3.11
you need to create config.py in settings/ folder. you can use /settings/config_template.py like an example
