### ISSUE TITLE
Help #2

### ISSUE THREAD

**Issue by kingofkillers91** [bilabon/chatgpt_telegram_bot#5]
Hi i'm having issue with this command:  cp settings/config_template.py settings/config.py
So this is how my config.py looks like:
![config](https://user-images.githubusercontent.com/48602339/224987776-fa31a34a-63de-497c-9bde-72e89f5743af.png)
this is how my config_template.py looks like:
![template](https://user-images.githubusercontent.com/48602339/224988801-8d8a63df-ea7e-4f61-8d7e-5ac9ab1814a3.png)
This is what's in the settings folder:
![image_2023-03-14_123603649](https://user-images.githubusercontent.com/48602339/224989130-957dd6c7-b724-484f-8df1-cc7701a280be.png)
So my issue is when i run the following command:  cp settings/config_template.py settings/config.py, i get this error:

![image_2023-03-14_123802452](https://user-images.githubusercontent.com/48602339/224989570-34984990-aa68-4e26-bb2f-f3e14d4b926d.png)

The name folder is correct, the files name are correct. Can you help me understand what's wrong?
thanks

**Comment by VladimirGavrilyuk** [comment]
Go to the folder where these configuration files are stored and run: mv -f config_template.py config.py

**Comment by bilabon** [comment]
@kingofkillers91 go to chatgpt_telegram_bot/ folder `cd chatgpt_telegram_bot/` and execute `cp settings/config_template.py settings/config.py`

**Comment by kingofkillers91** [comment]
Done working now. Thank you! Hope i won't have any more issue.
